server:
  port: 8080
spring:
  application:
    name: orchestrator-service

service:
  order: ${SERVICE_ORDER:http://localhost:8083/api/orders}
  inventory: ${SERVICE_INVENTORY:http://localhost:8084/api/inventory}